showroom = set()
showroom.add("Lexus")
showroom.add("CRV")
showroom.add("Highlander")
showroom.add("ZEN")
print(len(showroom))
showroom.add("Lexus")
showroom.update(["coupe", "BMW"])
print(len(showroom))
print(showroom)
showroom.add("Rangelover")
showroom.update(["Kia","Hyundai" ])
print(len(showroom))
print(showroom)

thisnumber = set()
thisnumber.add(1)
print(thisnumber)
thisnumber.update([1,2,3,4,5,6,6,7,7,8,9])
print(thisnumber)
thisnumber.update(["odd","even", "somenumber"])
print(thisnumber)
showroom.discard("Lexus")
showroom.remove("ZEN")
showroom.pop()
print(showroom)

junkyard = set()
junkyard.add("Audi")
junkyard.add("mazda")
junkyard.add("CRV")
junkyard.add("Lexus")
junkyard.add("Hyndai")
print(junkyard)

newcars = showroom.intersection(junkyard)
print(newcars)

morecars = showroom.union(junkyard)
print(morecars)
newshowroom = morecars.discard("Audi")
print(newshowroom)